### PR TITLE
make Testing module framework agnostic

### PR DESCRIPTION
**Pull request by vilinski**
`FsHttp.NUnit` can be renamed to `FsHttp.Testing` and `NUnit` reference removed ;)

### CODE REVIEW

**Comment by vilinski** [comment]
Hi! can you please comment this PR?

**Comment by ronaldschlenker** [comment]
Hi @vilinski, I merged the commit. Did you test the changes?

**Comment by vilinski** [comment]
Cool, thank you! Tried it again now - works with all 3 test frameworks

**Comment by ronaldschlenker** [comment]
Good, thanks for the PR. In the next release, we will ship that.

**Pull request merged**
