### PR TITLE
Reuse the same httpclient to avoid connection exhaustion on the machine

### PR DESCRIPTION
**Pull request by MaxDeg**
Recreating a new HttpClient each time is resource consuming and can lead to reach connection limit.
First attempt on fixing the issue. We could use it as a starting point to discuss

- Additional tests could be added
- SocketsHttpHandler with PooledConnectionLifetime is only available since netcoreapp2.1
- Domain for cookie are not useful as we set cookie per request (so no multiple domain)

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

### CODE REVIEW

**Comment by ronaldschlenker** [comment]
Hi Max. Thanks for your work. Just to let you know: I hope I‘ll be able to review and merge your PR soon.

**Comment by ronaldschlenker** [comment]
So I finally merged your pull request and published a prerelease here:

https://www.nuget.org/packages/SchlenkR.FsHttp/3.0.0-prerelease-1

I also appreciate your switch for Netstandard 2.1+.

Just for my understanding, your solution is based on

* A cancelation token (inside the DelegateHandler) that cancels the request after the specified Timeout (via TimeoutPropertyName)
* ConnectionPooling (for Netstandard 2.1 +)

Can you tell me why you set ```Timeout = Timeout.InfiniteTimeSpan``` in the HttpClient?

**Comment by MaxDeg** [comment]
Hello,

You’re welcome.
Indeed your understanding is correct. I set the timeout property to infinitetimespan to ensure the cancellation token is the only one handling the timeout. Default httpclient timeout is 30s so if someone want more we need to increase it.

________________________________

**Comment by RonaldSchlenker** [comment]
Finally, I switched back, thus I see the character of this library more as an alternative API to HttpClient, or a thin abstraction over it than a full wrapper. This is of course questionable. For that, a user can use the factories or transformers for the underlying HttpClient and HttpRequestMessage.

**Pull request merged**
